### ISSUE TITLE
開啟多網頁一直出現錯誤

### ISSUE THREAD

**Issue by NatLee** [tad0616/tad_web#4]
Tad 你好：

我在xoops新增這個模組後，進到模組設定都沒有問題

可是只要新增網頁就會出現錯誤

`Error : Error: Cannot use string offset as an array`

> 版本：
>  PHP 是 7.2.1 版
>  XOOPS 是 XOOPS 2.5 版

目前完全沒有頭緒問題出在哪

謝謝 =)

**Comment by tad0616** [comment]
因為他還不支援 7.1以上版本
最多只支援到 7.0
可能要等下一版吧～
